PowerAuras_ImagePack1_ImageInfo = {
	["Path"] = "Interface\\AddOns\\PowerAuras_ImagePack1\\Images\\",
	["FileList"] = {
		"ajaarg.tga",
		"ajbigsmile.tga",
		"ajbound.tga",
		"ajbringit.tga",
		"ajbroken.tga",
		"ajcarefull.tga",
		"ajchill.tga",
		"ajdowell.tga",
		"ajfront.tga",
		"ajgonnakick.tga",
		"ajguard.tga",
		"ajhai.tga",
		"ajhappy.tga",
		"ajhmmwut.tga",
		"ajhng.tga",
		"ajhonest.tga",
		"ajhrmm.tga",
		"ajlasso.tga",
		"ajleafstache.tga",
		"ajliedown.tga",
		"ajlolwut.tga",
		"ajnomnom.tga",
		"ajnotimpressed.tga",
		"ajoops.tga",
		"ajorly.tga",
		"ajropeswing.tga",
		"ajrun.tga",
		"ajsinferno.tga",
		"ajstare.tga",
		"ajuhok.tga",
		"ajwhatisthis.tga",
		"ajwhatisthisidonteven.tga",
		"ajwinning.tga",
		"ajwoo.tga",
		"ajwoo2.tga",
		"applejack.tga",
		"applejackangry.tga",
		"applejackburp.tga",
		"applejackcape.tga",
		"applejackelement.tga",
		"applejackface.tga",
		"applejacknom.tga",
		"applejackrope.tga",
		"applejackscared.tga",
		"applejackstand.tga",
		"applejackwoo.tga",
		"applejackwut.tga",
		"applejackwut2.tga",
		"applesplat.tga",
		"aj not impressed.tga",
		"aj pissed.tga",
		"aj pose.tga",
		"aj secretary.tga",
		"aj tail.tga",
		"aj whaat.tga",
		"aj.tga",
		"ajadorable.tga",
		"ajfalling.tga",
		"ajtailtoss.tga",

		"blank.tga",

		"radicaldash.tga",
		"rainbow.tga",
		"rainbowderp.tga",
		"rainbowelement.tga",
		"rainbowomigosh.tga",
		"rainbowsplat.tga",
		"rainbowstand.tga",
		"rainbowwhat.tga",
		"damnyoudash.tga",
		"sadstanddash.tga",
		"dashcheer.tga",
		"dashderping.tga",
		"skylookdash.tga",
		"dashgloat.tga",
		"dashheythere.tga",
		"dashissorry.tga",
		"dashnotsureifwant.tga",
		"dashohshitface.tga",
		"dashoo.tga",
		"dashsalute2.tga",
		"poserdash.tga",
		"dashwhat.tga",
		"dashwoop.tga",
		"dashwuuh.tga",
		"srsdash.tga",
		"winbadgedash.tga",
		"waitdash.tga",
		"winglessdash.tga",
		"wonderboltdash.tga",
		"egadsdash.tga",
		"guarddash.tga",
		"gutsdash.tga",
		"dejectdash.tga",
		"clouddash.tga",
		"fastflydash.tga",
		"armcrossdash.tga",
		"armordashfly.tga",
		"armordashfront.tga",
		"armordashstand.tga",
		"comeatmebrodash.tga",
		"sonicrainboom.tga",
		"scareddash.tga",
		"saddash.tga",
		"pokedash.tga",
		"ohshitdash.tga",
		"karatedash.tga",
		"hoofstanddash.tga",
		"galadash.tga",
		"flycooldash.tga",
		"sitfrontdash.tga",
		"glancedash.tga",
		"frontdash.tga",
		"flyingdash.tga",
		"facepalmdash.tga",
		"awesomedash.tga",
		"shadowclouddash.tga",
		"shadowdash.tga",
		"rainbow shadowbolt.tga",
		"rainbow always dresses in style.tga",
		"rainbow big cloud.tga",
		"rainbow big eyes.tga",
		"rainbow blargh.tga",
		"rainbow coffee.tga",
		"rainbow crouch.tga",
		"rainbow dashiedashie.tga",
		"rainbow disapoint.tga",
		"rainbow dursh.tga",
		"rainbow epic.tga",
		"rainbow gonna kill.tga",
		"rainbow grin.tga",
		"rainbow happydash.tga",
		"rainbow hop.tga",
		"rainbow intropose.tga",
		"rainbow is so gloaty.tga",
		"rainbow just sitting.tga",
		"rainbow mouthfull.tga",
		"rainbow nose dive.tga",
		"rainbow poser.tga",
		"rainbow ready to go.tga",
		"rainbow sensei.tga",
		"rainbow zoom.tga",
		"rainbow suprised.tga",
		"rainbow tail.tga",
		"rainbow wont laugh.tga",
		"rainbow wtfux.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",

		"aahshy.tga",
		"uhohshy.tga",
		"flutershyelement.tga",
		"dontlaughshy.tga",
		"flutterguard.tga",
		"haishy.tga",
		"huhshy.tga",
		"joyshy.tga",
		"ohnoesshy.tga",
		"cantwatchshy.tga",
		"saluteshy.tga",
		"shyfluttershy.tga",
		"skystareshy.tga",
		"sleepingshy.tga",
		"singfillyshy.tga",
		"fluttershy.tga",
		"smileyshy.tga",
		"squeeshy.tga",
		"cheershy.tga",
		"srsshy.tga",
		"worriedshy.tga",
		"yellingshy.tga",
		"windyshy.tga",
		"thestareshy.tga",
		"fluttershydance.tga",
		"fluttershyface.tga",
		"fluttershyhappy.tga",
		"fluttershyhesitate.tga",
		"fluttershyrage.tga",
		"fluttershysalute.tga",
		"fluttershyshy.tga",
		"fluttershysmile.tga",
		"fluttershysrs.tga",
		"fluttershystand.tga",
		"fluttershywut.tga",
		"fluttershyyay.tga",
		"flutterstance.tga",
		"flutterstandwings.tga",
		"crazysmileshy.tga",
		"forealshy.tga",
		"jumplookshy.tga",
		"frightnedshy.tga",
		"frontshy.tga",
		"armorshy.tga",
		"becarefullshy.tga",
		"fluttershy tada.tga",
		"privatepansy.tga",
		"fluttershy tail.tga",
		"fluttershy wuts this.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",

		"twilight.tga",
		"twilightawwh.tga",
		"twilightbigsmile.tga",
		"twilightbleh.tga",
		"twilightbook.tga",
		"twilightbutt.tga",
		"twilightcape.tga",
		"twilightchallenge.tga",
		"twilightconcentrate.tga",
		"twilightconfused.tga",
		"twilightcool.tga",
		"twilightcrazed.tga",
		"twilightcrown.tga",
		"twilightcurls.tga",
		"twilightdance.tga",
		"twilightdetermined.tga",
		"twilightdowell.tga",
		"twilighteheh.tga",
		"twilightelement.tga",
		"twilightfront.tga",
		"twilighthai.tga",
		"twilightheroic.tga",
		"twilighthey.tga",
		"twilighthigirls.tga",
		"twilighthmm.tga",
		"twilighthmm2.tga",
		"twilightismad.tga",
		"twilightitsfine.tga",
		"twilightlookdown.tga",
		"twilightmagic.tga",
		"twilightohai.tga",
		"twilightrage.tga",
		"twilightrarity.tga",
		"twilightreally.tga",
		"twilightsad.tga",
		"twilightsassy.tga",
		"twilightscarf.tga",
		"twilightsnake.tga",
		"twilightstressed.tga",
		"twilightstrut.tga",
		"twilighttrampled.tga",
		"twilighttumble.tga",
		"twilightugh.tga",
		"twilightwant.tga",
		"twilightwatchout.tga",
		"twilightwhee.tga",
		"twilightwhistle.tga",
		"twilightwhy.tga",
		"twilightwtf.tga",
		"twilightwtf2.tga",
		"twilightwutfront.tga",
		"twilightyeah.tga",
		"firetwi.tga",
		"sadtwilight.tga",
		"guardtwilight.tga",
		"happytwilight.tga",
		"insanetwilight.tga",
		"scrollcannon.tga",
		"happytwilight2.tga",
		"twilight angry.tga",
		"twilight bashfull.tga",
		"twilight derp.tga",
		"twilight embarrassed.tga",
		"twilight mad.tga",
		"twilight not amused.tga",
		"twilight pillow.tga",
		"twilight pointless.tga",
		"twilight tail.tga",
		"twilightbump.tga",
		"twilightdisgust.tga",
		"twilighthurl.tga",
		"twilightouch.tga",
		"twilightpose.tga",
		"twilightstartled.tga",
		"twilightworried.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",

		"biterarity.tga",
		"radiantrarity.tga",
		"rarity.tga",
		"notamusedrarity.tga",
		"ohmyrarity.tga",
		"ohyourarity.tga",
		"oopsierarity.tga",
		"owlrarity.tga",
		"perplexrarity.tga",
		"petrarity.tga",
		"wetrarity.tga",
		"worriedrarity.tga",
		"watchoutrarity.tga",
		"stancerarity.tga",
		"frontconfusedrarity.tga",
		"raritycape.tga",
		"rarityelement.tga",
		"rarityfront.tga",
		"rarityisserious.tga",
		"raritylaydown.tga",
		"raritynotamused.tga",
		"rarityoops.tga",
		"diamondeyesrarity.tga",
		"raritypose.tga",
		"rarityrun.tga",
		"raritysad.tga",
		"rarityslice.tga",
		"raritystance.tga",
		"rarityumpf.tga",
		"raritywaitwut.tga",
		"raritywut.tga",
		"rarityyell.tga",
		"princessrarity.tga",
		"rockcannon.tga",
		"tomandrarity.tga",
		"inquisrarity.tga",
		"introrarity.tga",
		"gesturerarity.tga",
		"grrrarity.tga",
		"fancyrarity.tga",
		"kararity.tga",
		"legrarity.tga",
		"ehehrarity.tga",
		"curlrarity.tga",
		"damnyoucatrarity.tga",
		"dawwrarity.tga",
		"derpity.tga",
		"rarity face turn.tga",
		"rarity grin.tga",
		"rarity intro pose.tga",
		"rarity lieing.tga",
		"rarity pouty.tga",
		"rarity princess not amused.tga",
		"rarity tail.tga",
		"rarityguard.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",

		"idontevenpinkie.tga",
		"nervouspinkie.tga",
		"ohyoupinkie.tga",
		"pieassaultpinkie.tga",
		"piethrowpinkie.tga",
		"piethrowpinkie2.tga",
		"pinkie.tga",
		"angrypinkie.tga",
		"pinkieangry.tga",
		"pinkieaway.tga",
		"pinkieblanket.tga",
		"pinkiebounces.tga",
		"pinkiecannon.tga",
		"pinkiecannon2.tga",
		"pinkiecannonshoot.tga",
		"pinkiechicken.tga",
		"pinkiedowell.tga",
		"pinkieeatspie.tga",
		"pinkieelement.tga",
		"pinkieface.tga",
		"pinkiefront.tga",
		"pinkiegrowl.tga",
		"pinkieguard.tga",
		"pinkiegummy.tga",
		"pinkiehand.tga",
		"pinkiehaters.tga",
		"pinkieheyy.tga",
		"pinkiejumps.tga",
		"pinkieliesdown.tga",
		"pinkieparty.tga",
		"pinkiepartyjump.tga",
		"pinkieshocked.tga",
		"pinkiesidehead.tga",
		"pinkieskylook.tga",
		"pinkiesnaps.tga",
		"pinkiesrs.tga",
		"pinkiestare.tga",
		"pinkiethrows.tga",
		"pinkietrips.tga",
		"pinkiewatchout.tga",
		"pinkiewhatisthis.tga",
		"pinkiewut.tga",
		"thispleasespinkie.tga",
		"confessingpinie.tga",
		"sadpinkie.tga",
		"toocutepinkie.tga",
		"wellduhpinkie.tga",
		"barrelpie.tga",
		"munchpinkie.tga",
		"juminpinie.tga",
		"haitharpinkie.tga",
		"bloatypie.tga",
		"gummybrainslug.tga",
		"pinkiechoke.tga",
		"dramaticpinkie.tga",
		"puddingderp.tga",
		"puddinghead.tga",
		"puddingstare.tga",
		"queenpinkie.tga",
		"chickenpie.tga",
		"chickenpinkie.tga",
		"chickensmile.tga",
		"pinkie pacman.tga",
		"pinkie radical.tga",
		"pinkie tail.tga",
		"pinkietrombone.tga",



		"luna.tga",
		"lunaapple.tga",
		"lunadoubt.tga",
		"lunafangs.tga",
		"lunafun.tga",
		"lunahai.tga",
		"lunasalute.tga",
		"lunasit.tga",
		"lunastand.tga",
		"lunawut.tga",
		"luna cloak full.tga",
		"luna cloaked.tga",
		"luna cloudy.tga",
		"luna discouraged.tga",
		"luna eclipsed.tga",
		"luna foreverrrr.tga",
		"luna head.tga",
		"luna hmm.tga",
		"luna kissmyhoof.tga",
		"luna lol oops.tga",
		"luna looking up.tga",
		"luna moar fun.tga",
		"luna needs attention.tga",
		"luna nightmare moon front.tga",
		"luna nightmare moon full.tga",
		"luna nightmare moon.tga",
		"luna nightmare vision.tga",
		"luna nightmaremoon your kidding.tga",
		"luna nightmaremoon.tga",
		"luna oh ok.tga",
		"luna oh thou.tga",
		"luna on cloud.tga",
		"luna shiny.tga",
		"luna small sleep.tga",
		"luna small stand.tga",
		"luna small.tga",
		"luna standing smiling.tga",
		"luna standing.tga",
		"luna wants.tga",
		"luna yarr.tga",
		"lunaeww.tga",
		"lunasmiling.tga",



		"alfalfamonster.tga",
		"celestia.tga",
		"celestiadoesntaprove.tga",
		"celestiafire.tga",
		"celestiafire2.tga",
		"celestiafly.tga",
		"celestiafront.tga",
		"celestialolz.tga",
		"celestiawut.tga",
		"celestia angry.tga",
		"celestia bow down.tga",
		"celestia is shiny.tga",
		"celestia lie down.tga",
		"celestia oh thou.tga",
		"celestia sitting.tga",
		"celestia stance.tga",
		"celestia the f.tga",

		"blank.tga",

		"cmc.tga",
		"cmcwut.tga",
		"bloombucket.tga",
		"bloomcopter.tga",
		"bloomderp.tga",
		"bloomdown.tga",
		"bloomduh.tga",
		"bloomhoopla.tga",
		"bloomhur.tga",
		"bloomincoming.tga",
		"bloomjump.tga",
		"bloomkick.tga",
		"bloomninja.tga",
		"bloomperplex.tga",
		"bloomsad.tga",
		"bloomsceptical.tga",
		"bloomstance.tga",
		"bloomtalentsing.tga",
		"bloomwtf.tga",
		"bloomwut.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",

		"scootaloo.tga",
		"scootcrazy.tga",
		"scootderp.tga",
		"scootdoesntcare.tga",
		"scoothuddle.tga",
		"scootlol.tga",
		"scootperplex.tga",
		"scootsad.tga",
		"scootspeechless.tga",
		"scootstance.tga",
		"scootstand.tga",
		"scoottalentsing.tga",
		"scootwut.tga",
		"dashaloo.tga",
		"scoothandstand.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",

		"sweetiebelle.tga",
		"sweetiederp.tga",
		"sweetiederp2.tga",
		"sweetiedoesntcare.tga",
		"sweetieperplex.tga",
		"sweetieproblem.tga",
		"sweetiesalute.tga",
		"sweetiesit.tga",
		"sweetiestare.tga",
		"sweetietalentsing.tga",
		"sweetieuhm.tga",
		"sweetiewaagh.tga",
		"sweetie evil.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",

		"confusedspike.tga",
		"creepyspike.tga",
		"spikebawz.tga",
		"villainspike.tga",
		"spikebreath.tga",
		"spikeburp.tga",
		"spikecreep.tga",
		"popeyespike.tga",
		"spikedisco.tga",
		"spikefacepalm.tga",
		"spikefancyhat.tga",
		"spikefreaks.tga",
		"spikegrin.tga",
		"spikehiccup.tga",
		"spikeknight.tga",
		"spikemustache.tga",
		"spikeno.tga",
		"spikeproud.tga",
		"spikewuup.tga",
		"spikeyuno.tga",
		"srsspike.tga",
		"stonedspike.tga",
		"swagspike.tga",
		"slyspike.tga",
		"runningspike.tga",
		"sadhatspike.tga",
		"suityspike.tga",
		"sidespike.tga",

		"blank.tga",
		"blank.tga",

		"derpy.tga",
		"derpyangry.tga",
		"derpychallenge.tga",
		"derpyface.tga",
		"derpyfight.tga",
		"derpyfront.tga",
		"derpyhappy2.tga",
		"derpyheh.tga",
		"derpykick.tga",
		"derpyoops.tga",
		"derpyplug.tga",
		"derpyretarded.tga",
		"derpyscared.tga",
		"derpyscrunch.tga",
		"derpysleep.tga",
		"derpystand.tga",
		"derpystand2.tga",
		"derpytoldoff.tga",
		"derpywut.tga",
		"derpywut2.tga",
		"happyderpy.tga",
		"muffincannon.tga",
		"derpy muffin.tga",
		"derpy tail.tga",



		"discord.tga",
		"discordlol.tga",
		"discordproblem.tga",
		"discordtroll.tga",

		"berrypunchwut.tga",
		"berryshock.tga",

		"bigmac.tga",

		"birthdaygummy.tga",
		"gummy.tga",
		"gummysneeze.tga",

		"carrottop.tga",

		"bonbonsuprized.tga",
		"bonbonguard.tga",

		"lyra.tga",
		"lyrasad.tga",
		"lyrayes.tga",
		"sunglasslyra.tga",
		"suprizedlyra.tga",
		"lyraguard.tga",

		"alleyway.tga",
		"attitude.tga",
		"filthy rich.tga",

		"cheerileedaww.tga",
		"cheerileehai.tga",
		"cheerileenotamused.tga",
		"cheerileestare.tga",
		"cheerlileescrunch.tga",
		"cheerilee tial.tga",
		"cheerilee whats that.tga",
		"cheerilee wonderfull.tga",

		"colgate.tga",

		"djpon3.tga",
		"djpon3guitar.tga",
		"djpon3stand.tga",
		"djpon3 watch out.tga",

		"drwhooves.tga",

		"echo.tga",

		"fancypants.tga",

		"fannyfreaks.tga",

		"firefly.tga",

		"fleurhappy.tga",
		"fleurpose.tga",

		"guard.tga",

		"hazmat.tga",

		"junebug.tga",

		"lilly.tga",
		"lilyscared.tga",

		"lotus.tga",

		"maredowell.tga",

		"quickfix.tga",

		"raindropsaction.tga",
		"raindropsohnoes.tga",
		"raindropsorly.tga",
		"raindropsuspicious.tga",
		"vikingraindrops.tga",

		"octaviaback.tga",
		"octaviawut.tga",

		"rose.tga",
		"rosestand.tga",
		"rose joy.tga",
		"rose peeved.tga",
		"rose sitting.tga",
		"rose smug.tga",
		"rose strut.tga",

		"seafoam.tga",
		"seafoamstare.tga",

		"sparklerwut.tga",

		"spitfire.tga",
		"spitfireadjust.tga",
		"spitfirefly.tga",

		"surprise.tga",

		"twinkleshine.tga",

		"trixie.tga",
		"trixieangry.tga",
		"trixiehai.tga",
		"trixieguard.tga",

		"zecora.tga",
		"zecorawatch.tga",
		"zecorawut.tga",

		"granny smith helmet.tga",
		"granny smith.tga",
		"granny smith young hat.tga",
		"granny smith young no hat.tga",
		"granny smith young.tga",

		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
		"blank.tga",
	},
}