--Russian localization
local L = BrokerToolBox:NewL("ruRU")
if not L then return end

L["clock_24hours"] = "24 часа" -- Needs review
L["clock_date"] = "Дата" -- Needs review
L["clock_days0"] = "Воскресенье" -- Needs review
L["clock_days1"] = "Понедельник" -- Needs review
L["clock_days2"] = "Вторник" -- Needs review
L["clock_days3"] = "Среда" -- Needs review
L["clock_days4"] = "Четверг" -- Needs review
L["clock_days5"] = "Пятница" -- Needs review
L["clock_days6"] = "Суббота" -- Needs review
L["clock_description"] = [=[Маленькие часы
Использован код из Broker_uClock (благодарности ethancentaurai)]=] -- Needs review
L["clock_leftclick"] = "Клик левой кнопкой: |cffffffffОткрыть менеджер времени|r" -- Needs review
L["clock_ltime"] = "Местное время" -- Needs review
L["clock_name"] = "Часы" -- Needs review
L["clock_noevents"] = "Нет событий" -- Needs review
L["clock_rightclick"] = "Клик правой кнопкой: |cffffffffНастройки|r" -- Needs review
L["clock_shiftleftclick"] = "Shift+клик левой кнопкой: |cffffffffОткрыть календарь|r" -- Needs review
L["clock_showcalendarevents"] = "Показать события в календаре" -- Needs review
L["clock_stime"] = "Серверное время" -- Needs review
L["clock_todayevents"] = "Сегодняшние события календаря" -- Needs review
L["clock_utime"] = "Время по Гринвичу" -- Needs review
L["core_author"] = "Автор" -- Needs review
L["core_click"] = "Клик: |cffffffffОткрыть выбор инструмента|r" -- Needs review
L["core_reloadrequired"] = "Необходима перезагрузка интерфейса..." -- Needs review
L["core_reloadui"] = "Перезагрузить интерфейс" -- Needs review
-- L["core_requires"] = "Requires"
L["core_version"] = "Версия" -- Needs review
L["equipment_Ctrlclick"] = "Ctrl+клик для удаления набора" -- Needs review
L["equipment_description"] = [=[Менеджер экипировки
Использован код из Broker_Equipment (благодарности p3lim)]=] -- Needs review
L["equipment_Leftclick"] = "Change with Left-click" -- Needs review
L["equipment_name"] = "Экипировка" -- Needs review
L["equipment_Rightclick"] = "Change with Right-click" -- Needs review
L["equipment_Shiftclick"] = "Shift+клик для обновления набора" -- Needs review
-- L["experience_click"] = "Click: |cffffffffSettings|r"
-- L["experience_description"] = "Shows your Experience"
-- L["experience_format"] = "Display Format"
-- L["experience_lvl"] = "Level"
-- L["experience_name"] = "Experience"
-- L["experience_OnMaxLevel"] = "Level Cap"
-- L["experience_percent"] = "Only Percent"
-- L["experience_rested"] = "Rested"
-- L["experience_ShowGuildXP"] = "Show Guild XP"
-- L["experience_today"] = "Today"
-- L["experience_value"] = "Only Value"
-- L["experience_value_percent"] = "Value and Percent"
-- L["experience_XPdisabled"] = "XPs Disabled"
-- L["freeBagSlots_backpack"] = "Backpack"
-- L["freeBagSlots_description"] = "Shows the free bag slots"
-- L["freeBagSlots_name"] = "Free Bag Slots"
L["location_description"] = "Показывает текущее местоположение" -- Needs review
L["location_highaccuracy"] = "Высокая точность координат" -- Needs review
L["location_leftclick"] = "Клик левой кнопкой: |cffffffffОткрыть карту мира|r" -- Needs review
L["location_name"] = "Позиция" -- Needs review
L["location_rightclick"] = "Клик правой кнопкой: |cffffffffНастройки|r" -- Needs review
L["location_showcords"] = "Показывать координаты" -- Needs review
L["location_showsubzone"] = "Показывать подзону" -- Needs review
L["microbutton_description"] = [=[WoW Микрокнопки
 + Показывать производительность и использование памяти аддонами]=]
L["microbutton_fps"] = "Кадров в секунду" -- Needs review
L["microbutton_HideBlizzButton"] = "Скрыть Микрокнопки Blizzard" -- Needs review
L["microbutton_leftclick"] = "Клик левой кнопкой: |cffffffffОткрыть Микрокнопки|r" -- Needs review
L["microbutton_LHome"] = "Позиция задержки" -- Needs review
L["microbutton_LWorld"] = "Глобальная задержка" -- Needs review
L["microbutton_memoryusage"] = "Использование памяти аддонами" -- Needs review
L["microbutton_name"] = "Микрокнопки" -- Needs review
L["microbutton_played"] = "Игровое время" -- Needs review
L["microbutton_playedlvl"] = "на этом уровне" -- Needs review
L["microbutton_rightclick"] = "Клик правой кнопкой: |cffffffffНастройки|r" -- Needs review
L["money_click"] = "Клик: |cffffffffНастройки|r" -- Needs review
L["money_description"] = "Показывает деньги игрока" -- Needs review
L["money_mymoney"] = "Деньги" -- Needs review
L["money_name"] = "Деньги" -- Needs review
L["money_RepairMoney"] = "на ремонт" -- Needs review
-- L["money_round"] = "Round to gold"
L["money_showtotal"] = "Показывать итого" -- Needs review
L["money_sum"] = "Итого" -- Needs review
L["money_unlimited"] = "неограничено" -- Needs review
--[==[ L["newMail_description"] = [=[Shows you, if you got a new mail.
|cffffffffDisables the minimap icon!|r]=] ]==]
-- L["newMail_name"] = "New Mail"
-- L["recountControl_datasource"] = "Datasource"
-- L["recountControl_description"] = "Simple modul to control Recount (Toggle, ...)"
-- L["recountControl_graphs"] = "Graphs"
-- L["recountControl_leftclick"] = "Leftclick: |cffffffffShow/Hide|r"
-- L["recountControl_name"] = "Recount Control"
-- L["recountControl_rightclick"] = "Rightclick: |cffffffffOpen menu|r"
L["repair_AllItemsGood"] = "Все вещи в порядке" -- Needs review
L["repair_autoguildrepair"] = "Автоматическая починка из гильдейского банка (если возможно)" -- Needs review
L["repair_autojunksell"] = "Автоматическая продажа мусора (вещи серого качества)" -- Needs review
L["repair_autorepair"] = "Автоматическая починка (если возможно)" -- Needs review
L["repair_BrokenWarning"] = "Предупреждение о состоянии вещей" -- Needs review
L["repair_BrokenWarningMsg"] = "Тревога: вещи почти сломаны (%s)" -- Needs review
L["repair_BrokenWarningSound"] = "Проигрывать звук предупреждения %s" -- Needs review
L["repair_BrokenWarningThreshold"] = "Порог предупреждения: %s" -- Needs review
L["repair_click"] = "Клик: |cffffffffОткрыть натсройки|r" -- Needs review
L["repair_description"] = [=[Показывает состояние вашей экипировки.
 + Предупреждение о состоянии, Автопочинка, Автоматическая продажа мусора]=]
L["repair_durability"] = "Состояние" -- Needs review
L["repair_name"] = "Починка" -- Needs review
L["repair_OFF"] = "Выкл" -- Needs review
L["repair_ON"] = "Вкл" -- Needs review
L["repair_Repaired"] = "Вещи починены за %s" -- Needs review
L["repair_RepairedFromGuild"] = "Вещи починены из гильдейского банка за %s" -- Needs review
L["repair_SellFor"] = "Вы продали мусора на %s." -- Needs review
-- L["reputation_description"] = "Shows your Reputation"
-- L["reputation_format"] = "Display Format"
-- L["reputation_leftclick"] = "Leftclick: |cffffffffOpen Reputation Frame|r"
-- L["reputation_name"] = "Reputation"
-- L["reputation_percent"] = "Only Percent"
-- L["reputation_rightclick"] = "Rightclick: |cffffffffSettings|r"
-- L["reputation_thisweek"] = "This Week"
-- L["reputation_value"] = "Only Value"
-- L["reputation_value_percent"] = "Value and Percent"
L["token_click"] = "Клик: |cffffffffНастройки|r" -- Needs review
L["token_description"] = "Показывать количество очков" -- Needs review
L["token_name"] = "Очки" -- Needs review
L["token_notoken"] = "У Вас нет очков" -- Needs review
L["token_PROFESSION"] = "Профессия" -- Needs review
L["token_PVE"] = "Групповое и рейдовое поздемелье" -- Needs review
L["token_PVP"] = "Игрок против игрока" -- Needs review
