BrokerToolBox:AddLocalization({
	clock_24hours = "24 часа", -- Needs review
	clock_date = "Дата", -- Needs review
	clock_days0 = "Воскресенье", -- Needs review
	clock_days1 = "Понедельник", -- Needs review
	clock_days2 = "Вторник", -- Needs review
	clock_days3 = "Среда", -- Needs review
	clock_days4 = "Четверг", -- Needs review
	clock_days5 = "Пятница", -- Needs review
	clock_days6 = "Суббота", -- Needs review
	clock_description = [=[Маленькие часы
Использован код из Broker_uClock (благодарности ethancentaurai)]=], -- Needs review
	clock_leftclick = "Клик левой кнопкой: |cffffffffОткрыть менеджер времени|r", -- Needs review
	clock_ltime = "Местное время", -- Needs review
	clock_name = "Часы", -- Needs review
	clock_noevents = "Нет событий", -- Needs review
	clock_rightclick = "Клик правой кнопкой: |cffffffffНастройки|r", -- Needs review
	clock_shiftleftclick = "Shift+клик левой кнопкой: |cffffffffОткрыть календарь|r", -- Needs review
	clock_showcalendarevents = "Показать события в календаре", -- Needs review
	clock_stime = "Серверное время", -- Needs review
	clock_todayevents = "Сегодняшние события календаря", -- Needs review
	clock_utime = "Время по Гринвичу", -- Needs review
	core_author = "Автор", -- Needs review
	core_click = "Клик: |cffffffffОткрыть выбор инструмента|r", -- Needs review
	core_reloadrequired = "Необходима перезагрузка интерфейса...", -- Needs review
	core_reloadui = "Перезагрузить интерфейс", -- Needs review
	core_version = "Версия", -- Needs review
	equipment_Ctrlclick = "Ctrl+клик для удаления набора", -- Needs review
	-- equipment_Leftclick = "Change with Left-click",
	-- equipment_Rightclick = "Change with Right-click",
	equipment_Shiftclick = "Shift+клик для обновления набора", -- Needs review
	equipment_description = [=[Менеджер экипировки
Использован код из Broker_Equipment (благодарности p3lim)]=], -- Needs review
	equipment_name = "Экипировка", -- Needs review
	-- experience_OnMaxLevel = "Level Cap",
	-- experience_ShowGuildXP = "Show Guild XP",
	-- experience_XPdisabled = "XPs Disabled",
	-- experience_click = "Click: |cffffffffSettings|r",
	-- experience_description = "Shows your Experience",
	-- experience_format = "Display Format",
	-- experience_lvl = "Level",
	-- experience_name = "Experience",
	-- experience_percent = "Only Percent",
	-- experience_rested = "Rested",
	-- experience_today = "Today",
	-- experience_value = "Only Value",
	-- experience_value_percent = "Value and Percent",
	location_description = "Показывает текущее местоположение", -- Needs review
	location_highaccuracy = "Высокая точность координат", -- Needs review
	location_leftclick = "Клик левой кнопкой: |cffffffffОткрыть карту мира|r", -- Needs review
	location_name = "Позиция", -- Needs review
	location_rightclick = "Клик правой кнопкой: |cffffffffНастройки|r", -- Needs review
	location_showcords = "Показывать координаты", -- Needs review
	location_showsubzone = "Показывать подзону", -- Needs review
	microbutton_HideBlizzButton = "Скрыть Микрокнопки Blizzard", -- Needs review
	microbutton_LHome = "Позиция задержки", -- Needs review
	microbutton_LWorld = "Глобальная задержка", -- Needs review
	microbutton_description = [=[WoW Микрокнопки
 + Показывать производительность и использование памяти аддонами]=], -- Needs review
	microbutton_fps = "Кадров в секунду", -- Needs review
	microbutton_leftclick = "Клик левой кнопкой: |cffffffffОткрыть Микрокнопки|r", -- Needs review
	microbutton_memoryusage = "Использование памяти аддонами", -- Needs review
	microbutton_name = "Микрокнопки", -- Needs review
	microbutton_played = "Игровое время", -- Needs review
	microbutton_playedlvl = "на этом уровне", -- Needs review
	microbutton_rightclick = "Клик правой кнопкой: |cffffffffНастройки|r", -- Needs review
	money_RepairMoney = "на ремонт", -- Needs review
	money_click = "Клик: |cffffffffНастройки|r", -- Needs review
	money_description = "Показывает деньги игрока", -- Needs review
	money_mymoney = "Деньги", -- Needs review
	money_name = "Деньги", -- Needs review
	money_showtotal = "Показывать итого", -- Needs review
	money_sum = "Итого", -- Needs review
	money_unlimited = "неограничено", -- Needs review
	repair_AllItemsGood = "Все вещи в порядке", -- Needs review
	repair_BrokenWarning = "Предупреждение о состоянии вещей", -- Needs review
	repair_BrokenWarningMsg = "Тревога: вещи почти сломаны (%s)", -- Needs review
	repair_BrokenWarningSound = "Проигрывать звук предупреждения %s", -- Needs review
	repair_BrokenWarningThreshold = "Порог предупреждения: %s", -- Needs review
	repair_OFF = "Выкл", -- Needs review
	repair_ON = "Вкл", -- Needs review
	repair_Repaired = "Вещи починены за %s", -- Needs review
	repair_RepairedFromGuild = "Вещи починены из гильдейского банка за %s", -- Needs review
	repair_SellFor = "Вы продали мусора на %s.", -- Needs review
	repair_autoguildrepair = "Автоматическая починка из гильдейского банка (если возможно)", -- Needs review
	repair_autojunksell = "Автоматическая продажа мусора (вещи серого качества)", -- Needs review
	repair_autorepair = "Автоматическая починка (если возможно)", -- Needs review
	repair_click = "Клик: |cffffffffОткрыть натсройки|r", -- Needs review
	repair_description = [=[Показывает состояние вашей экипировки.
 + Предупреждение о состоянии, Автопочинка, Автоматическая продажа мусора]=], -- Needs review
	repair_durability = "Состояние", -- Needs review
	repair_name = "Починка", -- Needs review
	-- reputation_description = "Shows your Reputation",
	-- reputation_format = "Display Format",
	-- reputation_leftclick = "Leftclick: |cffffffffOpen Reputation Frame|r",
	-- reputation_name = "Reputation",
	-- reputation_percent = "Only Percent",
	-- reputation_rightclick = "Rightclick: |cffffffffSettings|r",
	-- reputation_thisweek = "This Week",
	-- reputation_value = "Only Value",
	-- reputation_value_percent = "Value and Percent",
	token_PROFESSION = "Профессия", -- Needs review
	token_PVE = "Групповое и рейдовое поздемелье", -- Needs review
	token_PVP = "Игрок против игрока", -- Needs review
	token_click = "Клик: |cffffffffНастройки|r", -- Needs review
	token_description = "Показывать количество очков", -- Needs review
	token_name = "Очки", -- Needs review
	token_notoken = "У Вас нет очков", -- Needs review
},"ruRU")