--[[

************************************************************************

ptBR.lua

ptBR localization strings for Collectinator

File date: 2011-12-16T14:54:08Z 
Project version: 1.0.21

Please update:
http://www.wowace.com/projects/collectinator/localization/ptBR/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "ptBR", false)

if not L then return end

L["Lich King"] = "Lich Rei" -- Needs review
L["Name"] = "Nome" -- Needs review
L["PVP"] = "JxJ" -- Needs review
L["Reputation"] = "Reputação" -- Needs review
