if GetLocale() == "zhCN" then
	BINDING_HEADER_GOGOHEADER = "GoGoMount 按键绑定" -- Needs review
	BINDING_NAME_GOGOBINDING = "召唤坐骑/解散坐骑 按键绑定" -- Needs review
	BINDING_NAME_GOGOBINDING2 = "召唤/解散坐骑 (非飞行坐骑) 按键绑定" -- Needs review
	BINDING_NAME_GOGOBINDING3 = "召唤/解散多人坐骑 按键绑定" -- Needs review
	GoGo_Variables.Localize = {
	Skill = {
		Engineering = "工程学",
		Riding = "骑术",
		Tailoring = "裁缝",
	},
	String = {
		AutomaticallyRemoveBuffs = "自动移除影响召唤坐骑的Buff",
		AutoStartCrusaderAura = "Auto start Crusader Aura", -- Requires localization
		AutoStartCrusaderAura_Long = "Automatically start Crusader Aura when using GoGoMount to mount.", -- Requires localization
		Clear = "清除",
		ClearGlobalFavoriteMounts = "清除全局收藏",
		CurrentZone = "当前区域", -- Needs review
		CurrentZoneDescription = "Mounts flagged here as zone favorites will be the only mounts GoGoMount will use in this zone.  All other mounts and shape forms will be ignored.  Clearing this list will allow GoGoMount to use all mounts (or global favorites if set).", -- Requires localization
		CurrentZoneExclusions = "Current Zone Exclusions", -- Requires localization
		CurrentZoneFavorites = "当前地域收藏",
		DisableFlyingFromWater = "防止在水中时召唤飞行坐骑",
		DisableInCombat = "在战斗中禁用GoGoMount按钮", -- Needs review
		DisableInCombat_Long = "这个选项将在战斗中禁用GoGoMount 按钮。这个选项对于熊坦来说很有用。必须在战斗前来启用或禁用。", -- Needs review
		DisableUnknownMountNotices = "关闭未知坐骑提示",
		DisableUpdateNotices = "关闭更新提示",
		DruidFlightPreference = "在角色移动的情况下总是使用飞行形态",
		DruidOptions = "德鲁伊选项",
		DruidSingleClick = "一键切换至旅行形态",
		EnableAutoDismount = "开启自动解散坐骑",
		Favorites = "收藏",
		GlobalExclusions = "Global Exclusions", -- Requires localization
		GlobalExclusionsDescription = "Mounts will always be ignored.  Even if mounts selected here are set as favorites, they will not be used.", -- Requires localization
		GlobalFavorites = "全局收藏",
		GlobalPreferences = "全局优先",
		GlobalZoneDescription = "Preferred mounts defined here will only take effect if there are no zone specific mount favorites set for the current zone you are in.", -- Requires localization
		HunterOptions = "猎人选项", -- Needs review
		NewVersionFound = "GoGoMount 有新版本可更新",
		NoShapeInRandom = "Do not randomize shape forms with mounts", -- Requires localization
		PaladinOptions = "Paladin Options", -- Requires localization
		RemoveBuffs = "移除会影响召唤坐骑的Buffs",
		RemoveBuffs_Long = "GoGoMount将会尝试移除那些妨碍坐骑的Buf和姿态变形。这个仅为已知的Buff以及一些需要2次点击你的GoGoMount上马时才会执行。", -- Needs review
		UnknownMountFound = "在您的坐骑列表中发现一个未知的坐骑.请报告,以便在未来版本中加入",
		UseAspectOfThePackInstead = "Use Aspect Of The Pack instead of Aspect Of The Cheeta", -- Requires localization
		UseAspectOfThePackInstead_Long = "When enabled, GoGoMount will cast Aspect of the Pack instead of Aspect of the Cheetah.  Local zone or global settings override this setting.  If this is set to use Aspect of the Pack and you have Aspect of the Cheetah as a zone favorite, Aspect of the Cheetah will be used.", -- Requires localization
		ZoneExclusionsDescription = "Zone specific exclusions work the same as global exclusions but specific to this zone.  Any mount marked below as an exclusion for the zone you're currently in will never be summoned.", -- Requires localization
	},
	Talent = {
		AncestralSwiftness = "先祖迅捷",
		FeralSwiftness = "豹之迅捷",
	},
	Zone = {
		AbyssalDepths = "Abyssal Depths", -- Requires localization
		AmaniMountains = "Amani Mountains", -- Requires localization
		AQ40 = "安其拉神殿",
		AzuremystIsle = "秘蓝岛",
		BloodmystIsle = "秘血岛",
		CrumblingDepths = "Crumbling Depths", -- Requires localization
		Dalaran = "达拉然",
		DarkbreakCove = "Darkbreak Cove", -- Requires localization
		Deepholm = "Deepholm", -- Requires localization
		DireMaul = "厄运之槌",
		EversongWoods = "永歌森林",
		Ghostlands = "幽魂之地",
		Icecrown = "冰冠冰川",
		Ironforge = "铁炉堡",
		IsleOfQuelDanas = "奎爾達納斯之島",
		KrasusLanding = "克拉苏斯平台",
		LegionsRest = "Legion's Rest", -- Requires localization
		Lghorek = "L'ghorek", -- Requires localization
		Nespirah = "Nespirah", -- Requires localization
		ShimmeringExpanse = "Shimmering Expanse", -- Requires localization
		SholazarBasin = "索拉查盆地",
		SilvermoonCity = "银月城",
		SilverTideHollow = "Silver Tide Hollow", -- Requires localization
		TempleOfBethekk = "Temple of Bethekk", -- Requires localization
		TempleOfEarth = "Temple of Earth", -- Requires localization
		TenebrousCavern = "Tenebrous Cavern", -- Requires localization
		ThalassianPass = "Thalassian Pass", -- Requires localization
		ThalassianRange = "Thalassian Range", -- Requires localization
		TheCerebrillum = "The Cerebrillum", -- Requires localization
		TheExodar = "埃索达",
		TheFrozenSea = "冰冻之海",
		TheOculus = "魔环",
		TheStormPeaks = "风暴峭壁",
		TheTempleOfAtalHakkar = "阿塔哈卡神庙",
		TheUnderbelly = "达拉然下水道",
		TheVioletCitadel = "紫罗兰城堡",
		TheVortexPinnacle = "The Vortex Pinnacle", -- Requires localization
		TolBarad = "托尔巴拉德", -- Needs review
		TolBaradPeninsula = "Tol Barad Peninsula", -- Requires localization
		TwistingNether = "扭曲虚空",
		Vashjir = "Vashj'ir", -- Requires localization
		Wintergrasp = "冬拥湖",
	},
}

end --if